### ISSUE TITLE
Non-Descriptive and Repetitive Alt text

### ISSUE THREAD

**Issue by Eedle** [elinanaba/elinanaba.github.io#5]
**Type Of Issue:** Accessibility

**Across Entire Website**

**Description:**

“Deal Logo” implies the function of the image, but doesn’t explain what the deal logo looks like. The same holds true for “mani logo image”. Alternative example: “Mani logo: the word “mani”  in a thin black font”.

**URL:**  

- https://elinanaba.github.io/week-9/firstweb.html

- https://elinanaba.github.io/week-9/deals.html

- https://elinanaba.github.io/week-9/coupons.html

- https://elinanaba.github.io/week-9/freebies.html

- https://elinanaba.github.io/week-9/community.html

**File name:** 

- firstweb.html

- deals.html

- coupons.html

- freebies.html

- community.html

**For Home Page and Deals**

**Description:**

Alternative text “This is just an example” not very descriptive and is used for two different images.

**URL:**  

- https://elinanaba.github.io/week-9/deals.html

- https://elinanaba.github.io/week-9/firstweb.html

**File name:** 

- deals.html

- firstweb.html

**For Freebies**

**Description:**

Non-descriptive alt image text with grammatical errors is present on the “freebies” page: "bag with full of free samples”. Multiple product images bare the non-descriptive alt text “picture of sample stuff”.

**URL:** 

- https://elinanaba.github.io/week-9/freebies.html

**File name:** 

- freebies.html

**Comment by elinanaba** [comment]
Done! Thanks for the example. :)
